site_name: Reservas de Hotel
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# plugins:
#   - social
#   - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/matteeussPei
    - icon: fontawesome/brands/medium
      link: https://medium.com/@matteeuss
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matheus-peixoto/

copyright: |
  &copy; 2024 <a href="https://github.com/matteeussPei"  target="_blank" rel="noopener">Matheus Peixoto</a>